[project]
name = "noetl"
version = "0.1.18"
description = "Not Only Extract Transform Load Automation"
authors = [
    { name = "Kadyapam", email = "182583029+kadyapam@users.noreply.github.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
keywords = ["etl", "data-pipeline", "workflow", "automation"]
dependencies = [
    "fastapi>=0.115.6",
    "pydantic>=2.11.4",
    "aiofiles==24.1.0",
    "psycopg[binary,pool]>=3.2.7",
    "connectorx>=0.4.3",
    "sqlmodel>=0.0.24",
    "alembic>=1.15.2",
    "greenlet>=3.2.1",
    "uvicorn>=0.34.0",
    "requests>=2.32.3",
    "httpx>=0.28.1",
    "aiohttp>=3.11.18",
    "google-cloud-secret-manager>=2.24.0",
    "google-auth>=2.27.0",
    "google-cloud-logging>=3.12.1",
    "google-cloud-storage>=3.1.0",
    "google-cloud-firestore>=2.18.0",
    "python-multipart==0.0.20",
    "PyYAML>=6.0.1",
    "Jinja2>=3.1.6",
    "selenium>=4.32.0",
    "pycryptodome>=3.21",
    "urllib3>=2.3",
    "nats-py>=2.10.0",
    "Authlib>=1.5.1",
    "typer>=0.15.3",
    "click>=8.1.0,<8.2.0",
    "deepdiff>=8.4.2",
    "pandas>=2.2.3",
    "lark>=1.2.2",
    "duckdb>=1.3.0",
    "duckdb-engine>=0.17.0",
    "polars[pyarrow]>=1.30.0",
    "matplotlib>=3.10.3",
    "networkx>=3.5",
    "pydot>=4.0.1",
    "jupysql>=0.11.1",
    "jupyterlab>=4.4.3",
    "fsspec>=2025.5.1",
    "gcsfs>=2025.5.1",
    "boto3>=1.38.45",
    "azure-identity>=1.23.0",
    "azure-keyvault-secrets>=4.8.0"
]

[project.optional-dependencies]
dev = [
    "ipykernel>=6.29.4",
    "pytest>=8.1.1",
    "pytest-asyncio>=0.23.6",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.14.0"
]

[project.scripts]
noetl = "noetl.main:app"

[project.urls]
Homepage = "https://noetl.io"
Repository = "https://github.com/noetl/noetl"
Issues = "https://github.com/noetl/noetl/issues"

[tool.hatchling.build.targets.wheel]
packages = ["noetl", "ui"]

[tool.hatchling.build.targets.wheel.sources]
"noetl" = "noetl"
"ui" = "ui"

[tool.setuptools.package-data]
"ui" = ["**/*"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
