[project]
name = "noetl"
version = "0.0.2"
description = "notOnlyNoCodeExtractTransformLoad framework"
authors = [
    { name = "Kadyapam", email = "182583029+kadyapam@users.noreply.github.com" }
]
dependencies = [
    "fastapi>=0.115.6",
    "pydantic>=2.10.6",
    "aiofiles==24.1.0",
    "psycopg[pool]>=3.2.3",
    "uvicorn>=0.34.0",
    "requests>=2.32.3",
    "httpx>=0.28.1",
    "aiohttp>=3.11.13",
    "google-cloud-secret-manager>=2.18.2",
    "google-auth>=2.27.0",
    "google-cloud-logging>=3.10.0",
    "google-cloud-storage>=3.1.0",
    "google-cloud-firestore>=2.18.0",
    "python-multipart==0.0.20",
    "PyYAML>=6.0.1",
    "Jinja2>=3.1.4",
    "selenium>=4.12.0",
    "pycryptodome>=3.21",
    "urllib3>=2.3",
    "nats-py>=2.10.0",
    "Authlib>=1.5.1",
    "typer>=0.15.2"
]

[project.optional-dependencies]
dev = [
    "ipykernel>=6.29.4",
    "pytest>=8.1.1",
    "pytest-asyncio>=0.23.6",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.14.0"
]

[project.scripts]
noetl = "noetl.noetl:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
