apiVersion: noetl.io/v1
type: Playbook
metadata:
  playbookName: fetch-time-and-notify-to-slack
spec:
  vars:
    TIMEZONE: "{{ input.TIMEZONE }}"
    NOTIFICATION_CHANNEL: "{{ input.NOTIFICATION_CHANNEL }}"
    TIME_API: "http://worldtimeapi.org/api/timezone"
    FETCH_TIME_TASK: "fetch-time"
    NOTIFY_TASK: "send-notification"
  timeout: 120
  input: {}
  initialSettings:
    start: [fetch-time:{input: 1}, fetch-time:{input: 2}]
    state: ready
  transitions:
    INITIALIZED: [RUNNING, FAILED, TERMINATED]
    RUNNING: [SUSPENDED, COMPLETED, TERMINATED, FAILED]
    SUSPENDED: [RUNNING, TERMINATED, FAILED]
    COMPLETED: [INITIALIZED]
    FAILED: [INITIALIZED]
    TERMINATED: [INITIALIZED]
tasks:
  - taskName: fetch-time
    steps:
      - stepName: get-current-time
        description: "Get the current time from the World Time API"
        plugin: "http-handler:0_1_0"
        method: "GET"
        url: "{{ spec.vars.TIME_API }}/{{ spec.vars.TIMEZONE }}"
      - stepName: get-current-date
        description: "Get the current date from the World Time API"
        plugin: "http-handler:0_1_0"
        method: "GET"
        url: "{{ spec.vars.TIME_API }}/{{ spec.vars.TIMEZONE }}"
    switch:
      - nextTask:
        - send-notification
        condition: "{{ get-current-time.output.exitCode }} != 0"
        params: {getCurrentTimeRef: "{{ get-current-time.ref }}"}
  - taskName: send-notification
    steps:
      - stepName: send-notification
        description: "Send the fetched time notification"
        plugin: "http-handler:0_1_0"
        method: "POST"
        url: "{{ spec.vars.NOTIFICATION_CHANNEL }}"
        data:
          text: "The current time is {{ tasks.fetch-time.steps.get-current-time.response }}"
