apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: nats
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: cluster
      protocol: TCP
      port: 6222
      targetPort: 6222
