apiVersion: v1
kind: ConfigMap
metadata:
  name: noetl-config
  labels:
    app: noetl
data:
  TZ: "America/Chicago"
  LOG_LEVEL: "INFO"
  PYTHONPATH: "/opt/noetl"
  NOETL_DATA_DIR: "data"
  POSTGRES_USER: "demo"
  POSTGRES_DB: "demo_noetl"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_SCHEMA: "public"
  NOETL_USER: "noetl"
  NOETL_SCHEMA: "noetl"
  NOETL_ENABLE_UI: "false"