apiVersion: apps/v1
kind: Deployment
metadata:
  name: noetl
  labels:
    app: noetl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noetl
  template:
    metadata:
      labels:
        app: noetl
    spec:
      containers:
        - name: noetl
          image: python:3.12-slim
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: noetl-config
            - secretRef:
                name: noetl-secret
          volumeMounts:
            - name: noetl-data
              mountPath: /opt/noetl/data
          command: ["sh", "-c"]
          args:
            - |
              apt-get update && apt-get --no-install-recommends install -y \
                libpq-dev \
                git \
                && rm -rf /var/lib/apt/lists/*
              
              pip install noetl
              
              python -m noetl.main server --host 0.0.0.0 --port 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: noetl-data
          emptyDir: {}