apiVersion: noetl.io/v1
kind: Playbook
metadata:
  name: fetch-time-and-notify-slack
spec:
  vars:
    TIMEZONE: "{{ input.TIMEZONE }}"
    NOTIFICATION_CHANNEL: "{{ input.NOTIFICATION_CHANNEL }}"
    TIME_API: "http://worldtimeapi.org/api/timezone"
    FETCH_TIME_TASK: "fetch-time"
    NOTIFY_TASK: "send-notification"
  timeout: 120
  initialSettings:
    start: "{{ spec.vars.FETCH_TIME_TASK }}"
    state: ready
  transitions:
    ready: running
    running: [ completed, failed, terminated ]
  tasks:
    fetch-time:
      nats:
        command: "command.fetch-time.{{ metadata.name }}"
        event: "event.fetch-time.{{ metadata.name }}"
      steps:
        get-current-time:
          description: "Get the current time from the World Time API"
          plugin: "http-handler:0_1_0"
          method: "GET"
          url: "{{ spec.vars.TIME_API }}/{{ spec.vars.TIMEZONE }}"
        get-current-date:
          description: "Get the current date from the World Time API"
          plugin: "http-handler:0_1_0"
          method: "GET"
          url: "{{ spec.vars.TIME_API }}/{{ spec.vars.TIMEZONE }}"
      switch:
        - next: [ send-notification ]
          condition: "{{ $.fetch-time.get-current-time.output.exitCode }} != 0 && {{ $.fetch-time.get-current-date.exitCode }} != 0"
        - next: [ ]
          condition: "{{ data.tasks.check-repository.steps.check-repo-exists.exitCode }} == 0"
    send-notification:
      nats:
        input:
        command: "command.send-notification.{{ metadata.name }}"
        event: "event.send-notification.{{ metadata.name }}"
      description: "Send the fetched time notification"
      plugin: "http-handler:0_1_0"
      method: "POST"
      url: "{{ spec.vars.NOTIFICATION_CHANNEL }}"
      data:
        text: "The current time is {{ tasks.fetch-time.steps.get-current-time.response }}"
